remerge/workflows

- .github/workflows/go-checks.yml
- .github/workflows/go-modules.yml
- .github/workflows/upstream-check.yml
[trello](https://trello.com/c/tmyMQJxq/80-create-reusable-workflow-for-golang-lint-and-test)
> go package checks

- .github/workflows/go-checks.yml
[trello](https://trello.com/c/u85PGDLK/90-follow-up-speed-up-go-test-workflow)
> speed up go checks

- .github/workflows/go-build.yml
- .github/workflows/go-upload-s3.yml
[trello](https://trello.com/c/3BILLCW6/13-migrate-bidder)
> fix directory in S3 bucket

- .github/workflows/go-build.yml
- .github/workflows/go-checks.yml
- .github/workflows/go-modules.yml
[trello](https://trello.com/c/ADv3ZpCR/93-follow-up-automatically-detect-go-version-from-gomod)
> autodetect golang version

- .github/workflows/go-checks.yml
[trello](https://trello.com/c/nTedmmns/7-migrate-api-client-go)
> configurable lint target

- .github/workflows/go-build.yml
- .github/workflows/go-checks.yml
- .github/workflows/go-modules.yml
- .github/workflows/upstream-check.yml
[trello](https://trello.com/c/RULQy3c0/94-follow-up-switch-to-ssh-key-in-go-workflows)
> migrate go workflows to ssh key

- .github/workflows/pygo-lint-test.yml
Added git configuration for Go
> Moved Go config lower in PyGo workflow

- .github/workflows/go-lint-test.yml
- .github/workflows/python-lint-test.yml
Renamed Python lint-and-test workflow
> Added Git identity configuration

- .github/workflows/notify-repos-that-depend-on-me.yml
[Fully automate depupdater](https://trello.com/c/aidC1SAL/6143-fully-automate-depupdater)
> remove ref to PR branch

- .github/workflows/nomad-pack.yml
- .github/workflows/nomad.yml
https://remerge.atlassian.net/jira/software/c/projects/CORE/boards/152?modal=detail&selectedIssue=CORE-28
> CORE-28 | Notify github deployments for jira integration after nomad deployments

- .github/workflows/nomad-pack.yml
- .github/workflows/nomad.yml
Issue: https://github.com/remerge/trigger/actions/runs/5763577396
> Add workflow input so other workflows don't break

- .github/workflows/go-build.yml
- .github/workflows/go-checks.yml
- .github/workflows/go-docker.yml
- .github/workflows/go-lint-test.yml
- .github/workflows/go-modules.yml
- .github/workflows/pygo-lint-test.yml
Update from v2 to v4 to remove the deprecation warning
> Update setup-go action

- .github/workflows/actions-doc.yml
- .github/workflows/docker-gcr-push.yml
- .github/workflows/docker-v2.yml
- .github/workflows/docker.yml
- .github/workflows/go-build.yml
- .github/workflows/go-checks.yml
- .github/workflows/go-docker.yml
- .github/workflows/go-lint-test.yml
- .github/workflows/go-modules.yml
- .github/workflows/nomad-deploy.yml
- .github/workflows/nomad-pack.yml
- .github/workflows/nomad.yml
- .github/workflows/pygo-lint-test.yml
- .github/workflows/python-library-release.yml
- .github/workflows/python-lint-test.yml
- .github/workflows/slack-notify.yml
- .github/workflows/upstream-check.yml
- scripts/documentation/requirements.txt
> Revert "bump node version from 16 to 20"

- .github/workflows/docker-v2.yml
https://remerge.atlassian.net/browse/DATA-339
> Do not use shallow clones for docker build

- .github/workflows/docker-v2.yml
https://remerge.atlassian.net/browse/DATA-339
> Set default artifact registry repository

- .github/workflows/gcp-deploy-static-website.yml
https://remerge.atlassian.net/browse/CORE-260
> Core 260 create deployment workflow for static web applications

- .github/workflows/gcp-deploy-static-website.yml
https://remerge.atlassian.net/browse/CORE-260
> CORE-260 use envfile for static website deployment

- .github/workflows/static-website.yml
https://remerge.atlassian.net/browse/CORE-831
> Add updated static website workflow from v0 branch

- .github/workflows/deployment-start.yml
- .github/workflows/deployment.yml
- .github/workflows/docker.yml
- .github/workflows/static-website.yml
https://remerge.atlassian.net/browse/DSP-427
> Long sha for action slack deploy pipeline

- .github/workflows/deployment-start.yml
- .github/workflows/deployment.yml
- .github/workflows/docker.yml
- .github/workflows/static-website.yml
https://remerge.atlassian.net/browse/DSP-551
> Add support for Rollbar deployment and source maps

- .checkov.yml
- .copier-answers.yml
- .editorconfig
- .envrc
- .github/workflows/pre-commit.yml
- .github/workflows/static-website.yml
- .gitignore
- .pre-commit-config.yaml
- .prettierignore
- .prettierrc.js
- .vscode/settings.json
- .yamllint.yaml
- Makefile
https://remerge.atlassian.net/browse/DSP-886
> Delete static site sourcemaps before uploading to google cloud
